[package]
name = "dontupload/project"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
# Signal = "sleitnick/signal@2.0.1"
# Sift = "csqrl/sift@0.0.8"
